### ISSUE TITLE
OPENAI_API_BASE and OPENAI_API_KEY have no effect

### ISSUE THREAD

**Issue by yarray** [yufeikang/ai-cli#12]
I've set OPENAI_API_BASE and OPENAI_API_KEY as environment variable. The `ai ask` command shows "asking" forever while giving "--endpoint" and "--api-key" works.

After investigation I notice that a settings.json will be generated under ~/.config/ai_cli with default "api_key" and "endpoint" set. The issue may be caused by current configuration workflow and precedence. Manually changing the settings.json file also works.

**Comment by yufeikang** [comment]
The endpoint has a default value. The endpoint in the settings has a higher priority than the OPENAI_API_BASE in the environment variables. You can also make the environment variable work by setting ai setting --edit endpoint=.

Your suggestion is correct. I didn't explicitly define the default value differently. I will fix this issue in the next version. Thank you for your feedback.
