### ISSUE TITLE
could you please add support for Azure OpenAI

### ISSUE THREAD

**Issue by fieri** [yufeikang/ai-cli#19]
could you please add support for Azure OpenAI

**Comment by ishaan-jaff** [comment]
@fieri @yufeikang happy to take lead on this and help increase coverage using https://github.com/BerriAI/litellm 

let me know if this sounds good

**Comment by yufeikang** [comment]
Hello! Azure support is already available. Can you help test it? You need to set the environment variables AZURE_OPENAI_ENDPOINT and either AZURE_OPENAI_AD_TOKEN or AZURE_OPENAI_API_KEY.
