### ISSUE TITLE
Rich库无法输入多行聊天

### ISSUE THREAD

**Issue by hongwen000** [yufeikang/ai-cli#3]
如题。我看了rich库的实现，ask似乎没有输入多行的选项，导致没法复制多行到聊天窗口里。

**Comment by yufeikang** [comment]
rich 不支持，暂时还没有找到比较好的实现。随后会看一下。如果你有想法的话欢迎提出

ask的话可以暂时在终端通过 " 开输入多行

**Comment by yufeikang** [comment]
@hongwen000 请试试

ai setting --edit multi_line_input=yes

**Comment by hongwen000** [comment]
> @hongwen000 请试试
> 
> ai setting --edit multi_line_input=yes

太棒了，感谢您的更新
