### ISSUE TITLE
疑问 violation 邮件

### ISSUE THREAD

**Issue by kimitrois** [yufeikang/ai-cli#9]
一直收到openai 的邮件说：After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.

但却还能继续chat…

**Comment by yufeikang** [comment]
目前还没有收到过类似的邮件。这个工具只是使用openai最基本的一个api。请确认一下key有没有在什么地方泄露或者过多提问过违反规则的问题
